name: Working with GitHub secrets

on:
  push:
  workflow_dispatch:

jobs:
  workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install requirements
        run: pip install -r requirements.txt

      - name: Run script
        run: python script.py
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SUPER_SECRET: ${{ secrets.SUPER_SECRET }}
