name: Working with GitHub secrets

on:
  push:
  workflow_dispatch:

# permissions:
#   contents: write

jobs:
  workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install requests
        run: pip install requests

      - name: Output a secret
        run: echo ${{ secrets.SUPER_SECRET }}

      - name: Run script
        run: python script.py
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
